// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424215732_AddedRemainingTables")]
    partial class AddedRemainingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.BreakfastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("MainIngredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BreakfastFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 350,
                            IsVegetarian = true,
                            MainIngredient = "Flour",
                            Name = "Pancakes"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 250,
                            IsVegetarian = true,
                            MainIngredient = "Eggs",
                            Name = "Omelet"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 450,
                            IsVegetarian = false,
                            MainIngredient = "Bacon",
                            Name = "Bacon & Eggs"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 150,
                            IsVegetarian = true,
                            MainIngredient = "Milk",
                            Name = "Greek Yogurt"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 600,
                            IsVegetarian = false,
                            MainIngredient = "Tortilla",
                            Name = "Breakfast Burrito"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.FavoriteCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasMajorAirport")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteCities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasMajorAirport = true,
                            Name = "Cincinnati",
                            Population = 309000,
                            State = "Ohio"
                        },
                        new
                        {
                            Id = 2,
                            HasMajorAirport = true,
                            Name = "Nashville",
                            Population = 689000,
                            State = "Tennessee"
                        },
                        new
                        {
                            Id = 3,
                            HasMajorAirport = false,
                            Name = "Boulder",
                            Population = 108000,
                            State = "Colorado"
                        },
                        new
                        {
                            Id = 4,
                            HasMajorAirport = true,
                            Name = "Savannah",
                            Population = 147000,
                            State = "Georgia"
                        },
                        new
                        {
                            Id = 5,
                            HasMajorAirport = false,
                            Name = "Asheville",
                            Population = 94000,
                            State = "North Carolina"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Arts",
                            IsIndoor = false,
                            Name = "Photography",
                            SkillLevel = 7
                        },
                        new
                        {
                            Id = 2,
                            Category = "Technology",
                            IsIndoor = true,
                            Name = "Coding",
                            SkillLevel = 9
                        },
                        new
                        {
                            Id = 3,
                            Category = "Games",
                            IsIndoor = true,
                            Name = "Chess",
                            SkillLevel = 5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Outdoors",
                            IsIndoor = false,
                            Name = "Hiking",
                            SkillLevel = 8
                        },
                        new
                        {
                            Id = 5,
                            Category = "Culinary",
                            IsIndoor = true,
                            Name = "Cooking",
                            SkillLevel = 6
                        });
                });

            modelBuilder.Entity("FinalProject.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2004, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Mathematics",
                            FullName = "Duc Toan Le",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2007, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Nate Otten",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(2001, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Math",
                            FullName = "Bob Smith",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(2002, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Physics",
                            FullName = "Alice Wong",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(2000, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Statistics",
                            FullName = "Charlie Brown",
                            YearInProgram = "Junior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
