// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425001431_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.BreakfastFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("bit");

                    b.Property<string>("MainIngredient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BreakfastFoods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Calories = 350,
                            IsVegetarian = false,
                            MainIngredient = "Pork",
                            Name = "Sausage"
                        },
                        new
                        {
                            Id = 2,
                            Calories = 250,
                            IsVegetarian = true,
                            MainIngredient = "Flour",
                            Name = "Waffle"
                        },
                        new
                        {
                            Id = 3,
                            Calories = 450,
                            IsVegetarian = false,
                            MainIngredient = "Pork",
                            Name = "Bacon"
                        },
                        new
                        {
                            Id = 4,
                            Calories = 150,
                            IsVegetarian = true,
                            MainIngredient = "Oats",
                            Name = "Cereal"
                        },
                        new
                        {
                            Id = 5,
                            Calories = 300,
                            IsVegetarian = true,
                            MainIngredient = "Eggs",
                            Name = "Omelette"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.FavoriteCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("HasMajorAirport")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteCities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HasMajorAirport = true,
                            Name = "Cincinnati",
                            Population = 309000,
                            State = "Ohio"
                        },
                        new
                        {
                            Id = 2,
                            HasMajorAirport = true,
                            Name = "Atlanta",
                            Population = 498000,
                            State = "Georgia"
                        },
                        new
                        {
                            Id = 3,
                            HasMajorAirport = true,
                            Name = "Columbus",
                            Population = 921000,
                            State = "Ohio"
                        },
                        new
                        {
                            Id = 4,
                            HasMajorAirport = false,
                            Name = "Dayton",
                            Population = 137000,
                            State = "Ohio"
                        },
                        new
                        {
                            Id = 5,
                            HasMajorAirport = true,
                            Name = "Charlotte",
                            Population = 897000,
                            State = "North Carolina"
                        });
                });

            modelBuilder.Entity("FinalProject.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Arts",
                            IsIndoor = false,
                            Name = "Videography",
                            SkillLevel = 7
                        },
                        new
                        {
                            Id = 2,
                            Category = "Technology",
                            IsIndoor = true,
                            Name = "Coding",
                            SkillLevel = 9
                        },
                        new
                        {
                            Id = 3,
                            Category = "Outdoors",
                            IsIndoor = false,
                            Name = "rock Climbing",
                            SkillLevel = 8
                        },
                        new
                        {
                            Id = 4,
                            Category = "Sports",
                            IsIndoor = true,
                            Name = "Basketball",
                            SkillLevel = 8
                        },
                        new
                        {
                            Id = 5,
                            Category = "Fitness",
                            IsIndoor = true,
                            Name = "Running",
                            SkillLevel = 6
                        });
                });

            modelBuilder.Entity("FinalProject.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2004, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Mathematics",
                            FullName = "Duc Toan Le",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(2007, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Information Technology",
                            FullName = "Nate Otten",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(1946, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Business Administration",
                            FullName = "Jimmy Buffett",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(1948, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Kinesiology",
                            FullName = "Carl Weathers",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(1732, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Political Science",
                            FullName = "George Washington",
                            YearInProgram = "Senior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
