// <auto-generated />
using System;
using FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject.Models.Hobby", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkillLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Hobbies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Arts",
                            IsIndoor = false,
                            Name = "Photography",
                            SkillLevel = 7
                        },
                        new
                        {
                            Id = 2,
                            Category = "Technology",
                            IsIndoor = true,
                            Name = "Coding",
                            SkillLevel = 9
                        },
                        new
                        {
                            Id = 3,
                            Category = "Games",
                            IsIndoor = true,
                            Name = "Chess",
                            SkillLevel = 5
                        },
                        new
                        {
                            Id = 4,
                            Category = "Outdoors",
                            IsIndoor = false,
                            Name = "Hiking",
                            SkillLevel = 8
                        },
                        new
                        {
                            Id = 5,
                            Category = "Culinary",
                            IsIndoor = true,
                            Name = "Cooking",
                            SkillLevel = 6
                        });
                });

            modelBuilder.Entity("FinalProject.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CollegeProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearInProgram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Birthdate = new DateTime(2004, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Mathematics",
                            FullName = "Duc Toan Le",
                            YearInProgram = "Junior"
                        },
                        new
                        {
                            Id = 2,
                            Birthdate = new DateTime(1999, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Engineering",
                            FullName = "Jane Doe",
                            YearInProgram = "Senior"
                        },
                        new
                        {
                            Id = 3,
                            Birthdate = new DateTime(2001, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Math",
                            FullName = "Bob Smith",
                            YearInProgram = "Sophomore"
                        },
                        new
                        {
                            Id = 4,
                            Birthdate = new DateTime(2002, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Physics",
                            FullName = "Alice Wong",
                            YearInProgram = "Freshman"
                        },
                        new
                        {
                            Id = 5,
                            Birthdate = new DateTime(2000, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CollegeProgram = "Statistics",
                            FullName = "Charlie Brown",
                            YearInProgram = "Junior"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
